project_name: clerk
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: clerk
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
      - openbsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: openbsd
        goarch: arm
      - goos: openbsd
        goarch: arm64
universal_binaries:
  - replace: true
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto
brews:
  - name: clerk
    tap: # HomeBrew Tapをリリースするリポジトリ
      owner: asweed888
      name: homebrew-tap
    # ここは決め打ちで良い
    url_template: "https://github.com/asweed888/clerk/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author: # homebrew-tapにcommitするときに使うGitHubアカウント
      name: inadati
      email: dr.inadati@gmail.com
    homepage: "https://github.com/asweed888/clerk"
    description: "Declarative development framework clerk"     # 適当なdescription
    test: | # リリースビルド後の動作確認用のコマンド。--versionやhelpなどを指定すればよいだろう
      system "#{bin}/clerk help"
    install: |  # Goならばバイナリ名でOK
      bin.install "clerk"
