# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clerk < Formula
  desc "Declarative development framework clerk"
  homepage "https://github.com/asweed888/clerk"
  version "0.0.3"

  on_macos do
    url "https://github.com/asweed888/clerk/releases/download/v0.0.3/clerk_darwin_all.tar.gz"
    sha256 "5ad3c218ffc3b1852060b8ec38879751cf0286391d0341b4d9dbae99f5550346"

    def install
      bin.install "clerk"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/asweed888/clerk/releases/download/v0.0.3/clerk_linux_x86_64.tar.gz"
      sha256 "5c3684da7d25e06e6a9ea7ecc114520b21744681c8b3ee40e2cc8eb6c3396183"

      def install
        bin.install "clerk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/asweed888/clerk/releases/download/v0.0.3/clerk_linux_arm64.tar.gz"
      sha256 "8e5f7b6b5334fd8c514bed9558f24369e2aec497fadd1d00f96b7fc51577d1a0"

      def install
        bin.install "clerk"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/asweed888/clerk/releases/download/v0.0.3/clerk_linux_armv6.tar.gz"
      sha256 "be14baff5e74f985931fa495dbbf65ea5679d6382d19f671830784043d4c1f25"

      def install
        bin.install "clerk"
      end
    end
  end

  test do
    system "#{bin}/clerk help"
  end
end
